pg = pg or {}
pg.child2_shop = {
	{
		goods_type = 1,
		name = "体力+10（固定）",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2022,
		desc = "体力+10（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 1,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "知識+10（固定）",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2023,
		desc = "知識+10（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 2,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "器用+10（固定）",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2024,
		desc = "器用+10（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 3,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "感受性+10（固定）",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2025,
		desc = "感受性+10（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 4,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "気分+2（固定）",
		resource_num = 8,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2026,
		desc = "気分+2（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 5,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "体力+20（固定）",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2027,
		desc = "体力+20（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 6,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "知識+20（固定）",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2028,
		desc = "知識+20（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 7,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "器用+20（固定）",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2029,
		desc = "器用+20（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 8,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "感受性+20（固定）",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2030,
		desc = "感受性+20（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 9,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "気分+4（固定）",
		resource_num = 12,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2031,
		desc = "気分+4（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 10,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "体力+40（固定）",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2032,
		desc = "体力+40（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 11,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "知識+40（固定）",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2033,
		desc = "知識+40（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 12,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "器用+40（固定）",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2034,
		desc = "器用+40（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 13,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "感受性+40（固定）",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2035,
		desc = "感受性+40（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 14,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "気分+6（固定）",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2036,
		desc = "気分+6（固定）",
		goods_num = 1,
		resource_type = 1,
		id = 15,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "体力強化",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2001,
		desc = "予定獲得体力増加（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 16,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "知識強化",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2002,
		desc = "予定での知識入手量増加（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 17,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "器用強化",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2003,
		desc = "予定での器用入手量増加（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 18,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "感受性強化",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2004,
		desc = "予定での感受性入手量増加（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 19,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "幸運クーポン",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2005,
		desc = "購入後、20～100の財貨を獲得",
		goods_num = 1,
		resource_type = 1,
		id = 20,
		icon = "buff_2005"
	},
	{
		goods_type = 1,
		name = "体力ランダム強化",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2006,
		desc = "予定完了時、少量の体力をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 21,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "知識ランダム強化",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2007,
		desc = "予定完了時、少量の知識をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 22,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "器用ランダム強化",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2008,
		desc = "予定完了時、少量の器用をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 23,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "感受性ランダム強化",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2009,
		desc = "予定完了時、少量の感受性をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 24,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "体力ランダム強化+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2010,
		desc = "予定完了時、中量の体力をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 25,
		icon = "benefit_2_tineng_2"
	},
	{
		goods_type = 1,
		name = "知識ランダム強化+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2011,
		desc = "予定完了時、中量の知識をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 26,
		icon = "benefit_2_zhishi_2"
	},
	{
		goods_type = 1,
		name = "器用ランダム強化+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2012,
		desc = "予定完了時、中量の器用をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 27,
		icon = "benefit_2_shijian_2"
	},
	{
		goods_type = 1,
		name = "感受性ランダム強化+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2013,
		desc = "予定完了時、中量の感受性をランダムで獲得（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 28,
		icon = "benefit_2_ganzhi_2"
	},
	{
		goods_type = 1,
		name = "体力ランダム・次発強化",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2014,
		desc = "次ターン予定完了時、大量の体力をランダムで獲得",
		goods_num = 1,
		resource_type = 1,
		id = 29,
		icon = "benefit_2_tineng_3"
	},
	{
		goods_type = 1,
		name = "知識ランダム・次発強化",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2015,
		desc = "次ターン予定完了時、大量の知識をランダムで獲得",
		goods_num = 1,
		resource_type = 1,
		id = 30,
		icon = "benefit_2_zhishi_3"
	},
	{
		goods_type = 1,
		name = "器用ランダム・次発強化",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2016,
		desc = "次ターン予定完了時、大量の器用をランダムで獲得",
		goods_num = 1,
		resource_type = 1,
		id = 31,
		icon = "benefit_2_shijian_3"
	},
	{
		goods_type = 1,
		name = "感受性ﾗﾝﾀﾞﾑ・次発強化",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2017,
		desc = "次ターン予定完了時、大量の感受性をランダムで獲得",
		goods_num = 1,
		resource_type = 1,
		id = 32,
		icon = "benefit_2_ganzhi_3"
	},
	{
		goods_type = 1,
		name = "気分ランダム回復",
		resource_num = 25,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2018,
		desc = "ターン開始時、ランダムで気分が小回復（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 33,
		icon = "benefit_2_xinqing_1"
	},
	{
		goods_type = 1,
		name = "気分ランダム回復+",
		resource_num = 36,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2019,
		desc = "ターン開始時、ランダムで気分が中回復（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 34,
		icon = "benefit_2_xinqing_2"
	},
	{
		goods_type = 1,
		name = "気分ランダム回復++",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2020,
		desc = "ターン開始時、ランダムで気分が大回復（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 35,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 1,
		name = "気分ランダム回復(永続)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2021,
		desc = "ターン開始時、ランダムで気分が回復",
		goods_num = 1,
		resource_type = 1,
		id = 36,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 3,
		name = "行動力回復",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "購入すると、行動力+1",
		goods_num = 1,
		resource_type = 1,
		id = 37,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 3,
		name = "行動力回復+",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "購入すると、行動力+2",
		goods_num = 2,
		resource_type = 1,
		id = 38,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 1,
		name = "体力変換・知識",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2037,
		desc = "予定獲得体力増加、知識減少（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 39,
		icon = "benefit_2_tinengzhishiz"
	},
	{
		goods_type = 1,
		name = "知識変換・体力",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2038,
		desc = "予定獲得知識増加、体力減少（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 40,
		icon = "benefit_2_zhishitinengz"
	},
	{
		goods_type = 1,
		name = "器用変換・感受性",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2039,
		desc = "予定獲得器用増加、感受性減少（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 41,
		icon = "benefit_2_shijianganzhiz"
	},
	{
		goods_type = 1,
		name = "感受性変換・器用",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2040,
		desc = "予定獲得感受性増加、器用減少（3ターン）",
		goods_num = 1,
		resource_type = 1,
		id = 42,
		icon = "benefit_2_ganzhishijianz"
	},
	{
		goods_type = 1,
		name = "器用強化(切替)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2041,
		desc = "（循環切替）器用獲得増加←→器用獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 43,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "器用強化(切替)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2043,
		desc = "（循環切替）器用獲得増加←→器用獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 44,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "器用強化(切替)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2045,
		desc = "（循環切替）器用獲得増加←→器用獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 45,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "体力強化(切替)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2047,
		desc = "（循環切替）体力獲得増加←→体力獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 46,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "体力強化(切替)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2049,
		desc = "（循環切替）体力獲得増加←→体力獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 47,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "体力強化(切替)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2051,
		desc = "（循環切替）体力獲得増加←→体力獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 48,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "感受性強化(切替)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2053,
		desc = "（循環切替）感受性獲得増加←→感受性獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 49,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "感受性強化(切替)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2055,
		desc = "（循環切替）感受性獲得増加←→感受性獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 50,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "感受性強化(切替)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2057,
		desc = "（循環切替）感受性獲得増加←→感受性獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 51,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "知識強化(切替)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2059,
		desc = "（循環切替）知識獲得増加←→知識獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 52,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "知識強化(切替)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2061,
		desc = "（循環切替）知識獲得増加←→知識獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 53,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "知識強化(切替)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2063,
		desc = "（循環切替）知識獲得増加←→知識獲得減少",
		goods_num = 1,
		resource_type = 1,
		id = 54,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "特殊予定枠・壱",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2089,
		desc = "第1予定枠での予定のパラメータ増加量が小上昇",
		goods_num = 1,
		resource_type = 1,
		id = 55,
		icon = "benefit_2_xingcheng1_1"
	},
	{
		goods_type = 1,
		name = "特殊予定枠・壱+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2090,
		desc = "第1予定枠での予定のパラメータ増加量が中上昇",
		goods_num = 1,
		resource_type = 1,
		id = 56,
		icon = "benefit_2_xingcheng1_2"
	},
	{
		goods_type = 1,
		name = "特殊予定枠・壱++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2091,
		desc = "第1予定枠での予定のパラメータ増加量が大上昇",
		goods_num = 1,
		resource_type = 1,
		id = 57,
		icon = "benefit_2_xingcheng1_3"
	},
	{
		goods_type = 1,
		name = "奇数予定枠強化",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2092,
		desc = "奇数予定枠の予定のパラメータ増加量が小上昇",
		goods_num = 1,
		resource_type = 1,
		id = 58,
		icon = "benefit_2_xingchengji_1"
	},
	{
		goods_type = 1,
		name = "奇数予定枠強化+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2093,
		desc = "奇数予定枠の予定のパラメータ増加量が中上昇",
		goods_num = 1,
		resource_type = 1,
		id = 59,
		icon = "benefit_2_xingchengji_2"
	},
	{
		goods_type = 1,
		name = "奇数予定枠強化++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2094,
		desc = "奇数予定枠の予定のパラメータ増加量が大上昇",
		goods_num = 1,
		resource_type = 1,
		id = 60,
		icon = "benefit_2_xingchengji_3"
	},
	{
		goods_type = 1,
		name = "偶数予定枠強化",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2095,
		desc = "偶数予定枠の予定のパラメータ増加量が小上昇",
		goods_num = 1,
		resource_type = 1,
		id = 61,
		icon = "benefit_2_xingchengou_1"
	},
	{
		goods_type = 1,
		name = "偶数予定枠強化+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2096,
		desc = "偶数予定枠の予定のパラメータ増加量が中上昇",
		goods_num = 1,
		resource_type = 1,
		id = 62,
		icon = "benefit_2_xingchengou_2"
	},
	{
		goods_type = 1,
		name = "偶数予定枠強化++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2097,
		desc = "偶数予定枠の予定のパラメータ増加量が大上昇",
		goods_num = 1,
		resource_type = 1,
		id = 63,
		icon = "benefit_2_xingchengou_3"
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		39,
		40,
		41,
		42,
		43,
		44,
		45,
		46,
		47,
		48,
		49,
		50,
		51,
		52,
		53,
		54,
		55,
		56,
		57,
		58,
		59,
		60,
		61,
		62,
		63
	}
}
