pg = pg or {}
pg.island_furniture_template = {
	[10001] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 1,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 10,
		capacityCost = 10,
		id = 10001,
		model = "island/item/furniture/furniture01/furniture01_piano/prefab/pre_art_furniture01_piano",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "测试家具1",
		size = {
			5,
			5
		}
	},
	[20001] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 20001,
		model = "island/item/furniture/furniture01/furniture01_bathtub/prefab/pre_art_furniture01_bathtub01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "测试家具2",
		size = {
			2,
			3
		}
	},
	[30001] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30001,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/pre_autumn_furniture_s01_bamboobench01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "竹子长凳",
		size = {
			3,
			2
		}
	},
	[30002] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 0,
		capacityCost = 10,
		id = 30002,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bambootarget01/prefab/pre_autumn_furniture_s01_bambootarget01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "练习竹排",
		size = {
			1,
			1
		}
	},
	[30003] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30003,
		model = "island/item/furniture/jhs_autumn_furniture_s01/building02/prefab/pre_autumn_furniture_s01_building02",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "狸猫亭",
		size = {
			3,
			4
		}
	},
	[30004] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30004,
		model = "island/item/furniture/jhs_autumn_furniture_s01/chess01/prefab/pre_autumn_furniture_s01_chess01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "围棋石凳",
		size = {
			3,
			4
		}
	},
	[30005] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30005,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/pre_autumn_furniture_S01_gardentable01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "金鱼池塘",
		size = {
			4,
			4
		}
	},
	[30006] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30006,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/pre_autumn_furniture_S01_parterre01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "松树小景",
		size = {
			6,
			3
		}
	},
	[30007] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30007,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/pre_autumn_furniture_S01_rabbit01_B",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "黑白兔子摆件",
		size = {
			3,
			4
		}
	},
	[30008] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30008,
		model = "island/item/furniture/jhs_autumn_furniture_s01/pool02/prefab/pre_autumn_furniture_s01_pool02",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "木桥",
		size = {
			3,
			3
		}
	},
	[30009] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30009,
		model = "island/item/furniture/jhs_autumn_furniture_s01/pailou01/prefab/pre_autumn_furniture_s01_pailou01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "木门",
		size = {
			1,
			8
		}
	},
	[30010] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30010,
		model = "island/item/furniture/jhs_autumn_furniture_s01/sushitable01/prefab/pre_autumn_furniture_s01_sushitable01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "寿司桌",
		size = {
			3,
			3
		}
	},
	[30011] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30011,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "茶道伞下",
		size = {
			4,
			4
		}
	},
	[30012] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30012,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "园艺小桌子",
		size = {
			3,
			1
		}
	},
	[30013] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30013,
		model = "island/item/furniture/jhs_autumn_furniture_s01/wishingwell02/prefab/pre_autumn_furniture_s01_wishingwell02",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "狐狸供奉",
		size = {
			2,
			2
		}
	},
	[30014] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30014,
		model = "island/item/furniture/jhs_autumn_furniture_s01/pingfeng01/prefab/pre_autumn_furniture_s01_pingfeng01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "屏风",
		size = {
			5,
			1
		}
	},
	[30015] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30015,
		model = "island/item/furniture/jhs_autumn_furniture_s01/stonelamp01/prefab/pre_autumn_furniture_s01_stonelamp01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "小石灯",
		size = {
			1,
			1
		}
	},
	[30016] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30016,
		model = "island/item/furniture/jhs_autumn_furniture_s01/woodenlamp01/prefab/pre_autumn_furniture_s01_woodenlamp01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "木灯",
		size = {
			1,
			1
		}
	},
	[30017] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30017,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "兔子摆件灯",
		size = {
			1,
			1
		}
	},
	[30018] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30018,
		model = "island/item/furniture/jhs_autumn_furniture_s01/waterwell01/prefab/pre_autumn_furniture_s01_waterwell01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "石井",
		size = {
			2,
			2
		}
	},
	[30019] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30019,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "中石灯",
		size = {
			1,
			1
		}
	},
	[30020] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30020,
		model = "island/item/furniture/jhs_autumn_furniture_s01/stage01/prefab/pre_autumn_furniture_s01_stage01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "表演台",
		size = {
			3,
			5
		}
	},
	[30021] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 10,
		capacityCost = 10,
		id = 30021,
		model = "island/item/furniture/jhs_autumn_furniture_s01/treeswing01/prefab/pre_autumn_furniture_s01_treeswing01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "枫树秋千",
		size = {
			5,
			4
		}
	},
	[30022] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30022,
		model = "island/item/furniture/jhs_autumn_furniture_s01/wishingwell01/prefab/pre_autumn_furniture_s01_wishingwell01",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "狸猫兑换池",
		size = {
			3,
			3
		}
	},
	[30023] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 30023,
		model = "island/item/furniture/jhs_autumn_furniture_s01/bamboobench01/prefab/",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "卡皮巴拉摆件",
		size = {
			4,
			4
		}
	},
	[39999] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 3,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 39999,
		model = "island/item/furniture/furniture01/furniture01_flowerpot/prefab/pre_art_furniture01_flowerpot02",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "测试家具3",
		size = {
			2,
			3
		}
	},
	[40001] = {
		setNum = 99,
		describe = "",
		slot_cnt = 0,
		type = 4,
		hierarchy = 1,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 1,
		id = 40001,
		model = "island/item/furniture/furniture01/furniture01_floor/prefab/pre_art_furniture01_floor01b",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "测试家具4",
		size = {
			1,
			1
		}
	},
	[50001] = {
		setNum = 1,
		describe = "",
		slot_cnt = 0,
		type = 5,
		hierarchy = 3,
		rarity = 1,
		bt = "",
		prosperity = 5,
		capacityCost = 10,
		id = 50001,
		model = "island/item/furniture/furniture01/furniture01_table_05/prefab/pre_art_furniture01_table_05",
		timeline = "",
		themeId = 1,
		icon = "",
		name = "测试家具5",
		size = {
			4,
			1
		}
	},
	[60001] = {
		setNum = 1,
		describe = "",
		slot_cnt = 2,
		type = 6,
		hierarchy = 3,
		rarity = 1,
		bt = "island/nodecanvas/agora/test",
		prosperity = 5,
		capacityCost = 10,
		id = 60001,
		model = "island/item/furniture/furniture01/furniture01_table_03/prefab/pre_art_furniture01_table_03",
		timeline = "island/timeline/agora/test1",
		themeId = 1,
		icon = "",
		name = "测试家具6",
		size = {
			5,
			4
		}
	},
	[70001] = {
		setNum = 1,
		describe = "",
		slot_cnt = 1,
		type = 2,
		hierarchy = 3,
		rarity = 1,
		bt = "island/nodecanvas/agora/test",
		prosperity = 5,
		capacityCost = 10,
		id = 70001,
		model = "island/item/prop/item_massagechair/prefab/pre_art_item_massagechair01",
		timeline = "island/timeline/agora/test",
		themeId = 1,
		icon = "",
		name = "测试家具7",
		size = {
			4,
			4
		}
	},
	all = {
		10001,
		20001,
		30001,
		30002,
		30003,
		30004,
		30005,
		30006,
		30007,
		30008,
		30009,
		30010,
		30011,
		30012,
		30013,
		30014,
		30015,
		30016,
		30017,
		30018,
		30019,
		30020,
		30021,
		30022,
		30023,
		39999,
		40001,
		50001,
		60001,
		70001
	}
}
